### ISSUE TITLE
Variable slider speed may exceed maximum

### ISSUE THREAD

**Issue by stardust66** [ChristopherChudzicki/math3d#56]
Hi Mr. C. I'm Jason and I found your Github. Really cool project! The variable slider's speed can go beyond 8x when using the speed incrementing button. This happens:
<img width="246" alt="screen shot 2017-04-23 at 12 19 32 am" src="https://cloud.githubusercontent.com/assets/11802391/25310770/51b8c172-27bb-11e7-9ecd-d08563f3a5c9.png">
And the slider stops working. It's a really easy fix so I have a PR coming.

**Comment by ChristopherChudzicki** [comment]
resolved in #57
