### ISSUE TITLE
I started restructuring the files for Flask

### ISSUE THREAD

**Issue by stardust66** [ChristopherChudzicki/math3d#60]
I couldn't really wait until my APs are done. Django is packed full of features that this app probably doesn't need and it would make the directories look really crowded so I decided to pick up the python microframework Flask. I think I have the entire app running with Flask on heroku, but there might still be bugs. It's here: https://math3d.herokuapp.com/. From there it'll be easy to add databases and all that, but I need to learn how to do that. Probably should study for APs first.

Edit: The code is on the introduce-flask branch of my fork.

**Comment by stardust66** [comment]
About Heroku and Flask:

Flask is a python package for website backends. It's really easy to use. A basic app looks like this:
```
from flask import Flask
app = Flask(__name__)

@app.route('/')
def index():
    return "Hello, World!"
```
The example creates a website that displays "Hello, World!". `@app.route()` is used to indicate the url. The package has all of the functionality needed to interact with databases and do other server-side things.

Flask is WSGI compliant. https://www.python.org/dev/peps/pep-0333/. I don't know how exactly this works but basically WSGI is a specification for web apps so that a bunch of WSGI compliant packages can be used with your app, like python web servers.

The server I'm using is gunicorn (green unicorn) which serves WSGI apps. The command is just `gunicorn app:app` where the first app is `app.py` and the second one refers to the `app` object inside it.

Heroku offers VMs that run your web app for you. To get it running (for python apps), you need a `requirements.txt` generated by `pip freeze > requirements.txt`, which specifies the dependencies. Heroku uses this file to install python packages on their VM. Also you need a `Procfile` that specifies which command Heroku should run to launch the web app. My file just has `web: gunicorn app:app --log-file -` (Heroku requires a log file I think). After this you add Heroku as a git remote and just push to master. Heroku will automatically build the website.

**Comment by ChristopherChudzicki** [comment]
Cool. I am going to try and learn a bit more about Heroku and Flask!

And yeah, you should study for your APs!

**Comment by stardust66** [comment]
@ChristopherChudzicki Can I have whichever email you used to register on Heroku so I can add you as a collaborator?

**Comment by ChristopherChudzicki** [comment]
Yeah, I'll email you.

**Comment by stardust66** [comment]
I just added you. I made a bunch of barebone test pages for the database. Maybe you can make the actual pages for registering and logging in at some point. Now I need to work on an endpoint for handling requests from the javascript side, taking the serialized string and saving it as a Graph item in the database. Progress might be slow. I should really make myself study.
