### ISSUE TITLE
Store number of times accessed in database

### ISSUE THREAD

**Issue by ChristopherChudzicki** [ChristopherChudzicki/math3d#92]
It might be fun to add a metadata field showing the number of times a database graph has been accessed. Each time a user loads a graph from db, the counter would be incremented once.

**Comment by stardust66** [comment]
I can do this if you don't mind.

**Comment by ChristopherChudzicki** [comment]
@stardust66 That would be great!

**Comment by stardust66** [comment]
@ChristopherChudzicki I don't know where to display the property in the UI so I just added it as the `times_accessed` field to the `settings` object.

**Comment by ChristopherChudzicki** [comment]
Thanks for implementing this! 

I'm actually not sure that `times_accessed` needs to be displayed in the UI. Mostly it's metadata that I want to track because I think it could be useful in the future. I should probably have said this in the initial issue: Some reasons I see to track this data:

1. As a developer, it's interesting to know whether users are mostly creating new visualizations or loading old ones. 
2. If it ever became necessary to delete graphs from the database (e.g., for space), we could delete graphs based on number of views. (There are probably better ways)
3. Could be of interest to have a list of "popular graphs"

With that in mind, I also don't think we need to attach it to `math3d.settings`...let's remove line [line 235](https://github.com/ChristopherChudzicki/math3d/pull/93/files#diff-fb5aa1cd1261d08d02db6f7dc314d9abR235) in `index.html` for now. 

Other than that, I'm ready to merge it.

**Comment by stardust66** [comment]
@ChristopherChudzicki I just reverted the very last commit. That should work.

**Comment by ChristopherChudzicki** [comment]
Resolved by https://github.com/ChristopherChudzicki/math3d/pull/93
